const ARCHETYPES = [
  {
    key: "ai_agent_builders",
    label: "AI agent / voice agent builders",
    description:
      "Companies building AI agents, voice agents, conversational AI, AI receptionists, AI SDRs, AI support agents, AI calling products, dialers, voicebots, or call automation products.",
    includeSignals: [
      "voice agent",
      "ai agent",
      "conversational ai",
      "voicebot",
      "call automation",
      "ai receptionist",
      "dialer",
      "phone assistant",
      "call center automation",
      "voice ai",
      "ai calling",
    ],
    promptGuidance:
      "Return companies whose product is an AI/voice/call automation product. Prefer startups and software vendors building agents, dialers, or call automation.",
    evidenceKeywords: [
      "voice agent",
      "voice ai platform",
      "ai voice agent",
      "conversational ai platform",
      "voicebot",
      "ai dialer",
      "ai receptionist",
      "ai sdr",
      "voice automation",
      "phone ai agent",
      "ai calling platform",
      "speech ai",
      "voice assistant platform",
      "ai phone",
      "voice agent platform",
      "ai voice bot",
      "conversational voice ai",
      "phone automation",
      "voice bot platform",
      "ai caller",
      "automated voice agent",
      "voice ai assistant",
      "ai voice automation",
      "voice ai solution",
      "ai phone agent",
      "conversational ai agent",
      "voice ai product",
      "ai phone call",
      "voice-first ai",
      "ai call center",
      "ai-powered voice",
      "voice ai startup",
      "ai telephony agent",
      "conversational ai for call",
      "automated phone calls",
      "ai outbound calls",
      "voice ai calling",
      "ai voice calls",
      "ai inbound calls",
      "automated calling platform",
      "voice ai dialer",
      "ai voice receptionist",
      "ai agent",
      "ai appointment",
      "ai sales agent",
      "ai booking agent",
      "ai customer agent",
      "ai support agent",
      "ai concierge",
      "ai front desk",
      "ai hotel receptionist",
      "ai scheduling agent",
      "ai reservation agent",
      "ai order agent",
      "ai intake agent",
      "ai triage agent",
      "ai reminder agent",
      "ai follow-up agent",
      "ai qualification agent",
      "ai outreach agent",
      "ai onboarding agent",
      "ai screening agent",
      "ai dispatch agent",
      "ai nurse line",
      "ai health assistant",
      "ai benefits agent",
      "ai claims agent",
      "ai collections agent",
      "ai loan agent",
      "ai mortgage agent",
      "ai insurance agent",
      "ai travel agent",
      "ai hospitality agent",
      "ai restaurant agent",
      "ai retail agent",
      "ai real estate agent",
      "ai recruitment agent",
      "ai hr agent",
      "ai payroll agent",
      "ai compliance agent",
      "ai fraud agent",
      "ai verification agent",
      "ai routing agent",
      "ai escalation agent",
      "ai callback agent",
      "ai voicemail agent",
      "ai transcription agent",
      "ai translation agent",
      "ai interpreter",
      "hotel ai",
      "travel ai",
      "healthcare ai agent",
      "fintech ai agent",
      "insurance ai agent",
      "restaurant ai",
      "real estate ai",
      "retail ai",
      "automated receptionist",
      "virtual receptionist",
      "digital receptionist",
      "virtual front desk",
      "automated front desk",
      "virtual concierge",
      "digital concierge",
      "ai phone answering",
      "automated phone answering",
      "ai call handling",
      "ai call routing",
      "voice-based ai",
      "speech-driven ai",
      "phone-first ai",
      "call-first ai",
      // --- Added: high-confidence 2-3 word combos (voice/phone/speech specific) ---
      "speech analytics",
      "call analytics",
      "call transcription",
      "speech recognition",
      "voice recognition",
      "speech synthesis",
      "text to speech",
      "speech to text",
      "voice synthesis",
      "voice cloning",
      "dialogue system",
      "voice platform",
      "speech platform",
      "voice technology",
      "speech technology",
      "voice interface",
      "speech interface",
      "conversational ai",
      "dialog management",
      "ai translator",
      "voice translator",
      "speech translator",
      "call automation",
      "call ai",
      "phone ai",
      "phone automation",
      "speech ai",
      "voice chatbot",
      "ivr ai",
      "ivr automation",
      "voice self-service",
      "call deflection",
      "automated calls",
      "automated calling",
      "outbound dialer",
      "smart dialer",
      "progressive dialer",
      "ai conversation",
      "multilingual ai",
      "voice commerce",
      "voice ordering",
      "phone ordering",
      "voice booking",
      "phone booking",
      "voice scheduling",
      "phone scheduling",
      "automated reminders",
      "call reminder",
      "voice reminder",
      "phone reminder",
    ],
  },
  {
    key: "vertical_phone_workflows",
    label: "Vertical software with phone-native workflows",
    description:
      "Healthcare, fintech, collections, patient access, scheduling, verification, concierge, service operations, or customer support software where calls are central to the workflow.",
    includeSignals: [
      "patient access",
      "appointment scheduling",
      "collections",
      "verification",
      "call center",
      "phone support",
      "service dispatch",
      "care coordination",
      "booking support",
      "reminders",
    ],
    promptGuidance:
      "Return software companies where calls are structurally central to the workflow: patient comms, collections, verification, service ops, booking/support, or contact center operations.",
    evidenceKeywords: [
      "patient access",
      "patient scheduling",
      "appointment scheduling software",
      "patient reminder calls",
      "collections software",
      "automated verification calls",
      "care coordination platform",
      "patient outreach",
      "medical scheduling",
      "healthcare call center",
      "outbound call center",
      "inbound call center",
      "phone triage",
      "patient communication platform",
      "healthcare phone system",
      "patient callback",
      "telehealth scheduling",
      "medical call center",
      "healthcare communication platform",
      // --- Added: high-confidence 2-3 word combos (voice/call specific only) ---
      "patient communication",
      "care coordination",
      "healthcare scheduling",
      "medical scheduling",
      "clinical workflow",
      "referral management",
      "speech analytics",
      "call analytics",
      "quality monitoring",
      "call recording",
      "field service",
      "service dispatch",
      "debt collection",
      "queue management",
      "callback management",
      "debt collection",
      "payment collection",
      "identity verification",
    ],
  },
  {
    key: "cx_operators",
    label: "Contact-center / BPO / CX operators",
    description:
      "BPOs, contact-center operators, and CX outsourcers with obvious high-volume phone workflows and automation needs.",
    includeSignals: ["bpo", "contact center", "cx", "customer support", "outsourcing", "call center"],
    promptGuidance:
      "Return BPOs, contact-center operators, and CX services firms where call volume is core to the business.",
    evidenceKeywords: [
      "bpo",
      "contact center operator",
      "call center services",
      "cx outsourcing",
      "call center outsourcing",
      "customer support outsourcing",
      "business process outsourcing",
      "call center as a service",
      "managed call center",
      "contact center services",
      "outsourced call center",
      "customer experience outsourcing",
      "teleservices",
      "telemarketing services",
      "help desk outsourcing",
      "customer service center",
      "call center operations",
      "inbound call handling",
      "outbound call services",
      "customer support operations",
      "technical support center",
      // --- Added: high-confidence 2-3 word combos ---
      "contact center outsourcing",
      "call center outsourcing",
      "outsourced contact center",
      "outsourced customer",
      "bpo services",
      "cx operations",
      "call center operations",
      "support outsourcing",
      "workforce management",
      "workforce optimization",
      "agent scheduling",
      "queue management",
      "skill-based routing",
      "interactive voice",
      "voice response",
      "call handling",
      "phone support",
      "outbound campaigns",
      "lead generation",
      "collection services",
      "payment recovery",
    ],
  },
  {
    key: "embedded_voice_platforms",
    label: "Platform builders embedding telephony / voice automation",
    description:
      "Software companies where telephony, SIP, call routing, numbers, or AI calling is a core product component.",
    includeSignals: ["telephony", "sip", "call routing", "numbers", "ivr", "voice api", "calling"],
    promptGuidance:
      "Return platform builders embedding telephony, SIP, call routing, numbers, IVR, or AI calling into a broader product.",
    evidenceKeywords: [
      "telephony platform",
      "call routing",
      "ivr platform",
      "voice api",
      "programmable calling",
      "phone system",
      "cloud phone",
      "virtual numbers",
      "voip platform",
      "cloud pbx",
      "click to call",
      "embedded calling",
      "voice infrastructure",
      "call tracking platform",
      "phone verification api",
      "sms and voice api",
      "cpaas platform",
      "number provisioning",
      "call recording platform",
      "voip for business",
      "unified communications platform",
      "web rtc platform",
      "sip calling",
      "phone call api",
      "voice gateway",
      "call analytics platform",
      "telecom api",
      "dialer platform",
      "auto dialer software",
      "predictive dialer",
      "power dialer",
      // --- Added: high-confidence 2-3 word combos ---
      "voice api",
      "phone api",
      "calling api",
      "sms api",
      "telephony api",
      "phone numbers",
      "virtual numbers",
      "number management",
      "call tracking",
      "call routing",
      "call recording",
      "call transcription",
      "call analytics",
      "ivr system",
      "ivr platform",
      "auto attendant",
      "call queue",
      "webrtc calling",
      "browser calling",
      "click to call",
      "click to dial",
      "embedded phone",
      "softphone",
      "web phone",
      "voip calling",
      "voice gateway",
      "fax api",
      "programmable voice",
      "programmable sms",
      "cloud telephony",
      "cloud communications",
    ],
  },
];

const NEGATIVE_CLASSES = [
  {
    key: "carriers_isps",
    label: "Carriers / ISPs / network operators",
    keywords: [
      "telecommunications",
      "telecom",
      "wireless",
      "carrier",
      "mobile network",
      "internet service provider",
      "isp",
      "broadband",
      "fiber network",
      "network operator",
      "wholesale voice",
      "wholesale sms",
    ],
  },
  {
    key: "communications_vendors",
    label: "CPaaS / UCaaS / CCaaS / communications vendors",
    keywords: [
      "cpaas",
      "communications platform",
      "ucaas",
      "ccaas",
      "contact center software",
      "voip provider",
      "sip trunk provider",
      "sms gateway",
      "programmable messaging",
      "communications api",
      "unified communications",
      "ip pbx",
      "cloud pbx",
      "cloud phone system",
      "business phone system",
      "voip phone",
      "pbx system",
      "hosted pbx",
      "virtual pbx",
      "softphone",
      "call center software",
    ],
  },
  {
    key: "generic_software",
    label: "Generic software / marketplace / broad ecommerce",
    keywords: [
      "marketplace",
      "graphic design",
      "design platform",
      "project management",
      "accounting software",
      "ecommerce marketplace",
      "shopping platform",
      "real estate marketplace",
      "broad ecommerce",
      "sales platform",
      "sales software",
      "marketing platform",
      "marketing software",
      "crm platform",
      "hr platform",
      "hr software",
      "recruitment platform",
      "payroll software",
      "employee management",
      "collaboration software",
      "product management",
      "analytics platform",
      "data platform",
      "business intelligence",
      "dashboard software",
      "rpa platform",
      "robotic process",
      "process automation",
      "workflow automation",
      "task management",
      "document management",
      "content management",
      "knowledge management",
      "learning platform",
      "education platform",
      "edtech platform",
      "parking platform",
      "parking app",
      "appointment booking platform",
      "real estate platform",
    ],
  },
  {
    key: "broad_finance_without_signal",
    label: "Broad finance / banking / insurance without explicit voice signal",
    keywords: [
      "bank", "banking", "wealth management", "retail banking",
      "life insurance", "credit card", "card company", "financial group",
      "insurance company", "asset management", "securities firm",
      "investment firm", "financial services company",
    ],
  },
  {
    key: "non_voice_healthcare_fintech",
    label: "Healthcare / fintech without voice/phone product",
    keywords: [
      "doctor booking",
      "appointment scheduling app",
      "medical records",
      "electronic health records",
      "health insurance platform",
      "insurtech platform",
      "payment processing",
      "payment gateway",
      "lending platform",
      "neobank",
      "banking app",
      "investment platform",
      "trading platform",
      "regtech platform",
      "compliance software",
      "crypto platform",
      "blockchain platform",
    ],
  },
  {
    key: "media_news_publishing",
    label: "News / media / publishing / blog sites",
    keywords: [
      "news and views",
      "news site",
      "blog",
      "publisher",
      "media company",
      "journalism",
      "magazine",
      "newsletter",
      "podcast platform",
      "content platform",
      "information site",
    ],
  },
  {
    key: "agencies_consulting",
    label: "Agencies / consulting / IT services without voice product",
    keywords: [
      "digital agency",
      "advertising agency",
      "marketing agency",
      "consulting firm",
      "it consulting",
      "system integrator",
      "software development agency",
      "web development agency",
      "custom software development",
      "staffing agency",
      "recruitment agency",
      "training center",
      "consultancy",
      "cabinet de conseil",
      "advisory firm",
      "management consulting",
      "strategy consulting",
      "technology consulting",
      "data consulting",
      "ai consulting",
      "professional services firm",
      "it services firm",
      "it services",
      "outsourcing company",
      "engineering consultancy",
      "boutique consulting",
      "cabinet de",
      "beratung",
      "conseil en",
      "data & ai consulting",
      "data and ai consulting",
      "software development company",
      "software house",
      "software development studio",
      "development agency",
      "tech agency",
      "it solutions",
      "it services and consulting",
      "information technology services",
      "technology services",
      "digital transformation",
      "it provider",
      "system development",
      "custom development",
      "application development",
      "software factory",
    ],
  },
  {
    key: "phone_support_only",
    label: "Companies where 'phone support' is the only signal",
    keywords: [
      "phone support",
      "customer service center",
      "customer support operations",
    ],
  },
  {
    key: "healthcare_provider",
    label: "Hospitals / clinics / healthcare providers (not tech companies)",
    keywords: [
      "krankenhaus",
      "hôpital",
      "hospital",
      "clinic",
      "healthcare provider",
      "medical center",
      "health system",
      "healthcare group",
      "care provider",
      "nhs trust",
      "nhs foundation",
      "medical university",
      "university hospital",
      "clinical center",
      "sanatorium",
      "care home",
      "nursing home",
      "healthcare network",
      "ospital",
      "allgemeines krankenhaus",
      "centre hospitalier",
      "körház",
      "nemocnica",
      "bolnica",
      "sairaala",
    ],
  },
  {
    key: "appointment_scheduling_only",
    label: "Appointment scheduling / booking-only platforms without voice",
    keywords: [
      "appointment scheduling app",
      "online appointment booking",
      "patient portal",
      "online scheduling",
      "booking platform",
      "terminbuchung",
      "terminplaner",
      "appointment booking platform",
      "online termin",
      "doctor booking",
      "medical marketplace",
      "health marketplace",
      "visit marketplace",
    ],
  },
];

module.exports = { ARCHETYPES, NEGATIVE_CLASSES };
